---
- name: Install bind utils
  ansible.builtin.yum:
    name: bind-utils
    state: present

- name: Check ip address of the fqdn
  ansible.builtin.command: "nslookup {{ item }}.{{ cluster_name }}.{{ domain }}"
  register: cmd_output
  ignore_errors: true

- name: Check nslookup result
  ansible.builtin.fail:
    msg: "{{ item }}.{{ cluster_name }}.{{ domain }} cannot be found."
  when: cmd_output.rc != 0

- name: Check the ip address of fqdn
  ansible.builtin.set_fact:
    ipip: "{{ cmd_output.stdout_lines[-1] | regex_replace('^(Address:\\s+)([0-9]+\\..*)$', '\\2') }}"

- name: Fail the task when ip address of api is not equal to haproxy
  ansible.builtin.fail:
    msg: "{{ item }}.{{ cluster_name }}.{{ domain }} should equal to the haproxy ip address."
  when: ipip != haproxy_ip
