---
- name: Open firewall ports
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  loop: "{{ haproxy_fw_ports }}"

- name: Reload firewalld rules
  ansible.builtin.command:
    cmd: "firewall-cmd --reload"

- name: Install haproxy package
  ansible.builtin.yum:
    name: haproxy
    state: present

# - name: Fail the task when ssh public key is not defined
#   ansible.builtin.fail:
#     msg: "Variable ssh_pub_key is not defined."
#   when: ssh_pub_key is not defined

- name: Update haproxy.cfg
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'

- name: Update SELinux
  command: "setsebool -P haproxy_connect_any=1"

- name: Start haproxy service
  ansible.builtin.service:
    name: haproxy
    state: restarted
    enabled: true
