---
- name: Install OCP
  hosts: haproxy
  gather_facts: true
  vars_files:
    - vars.yml

  tasks:
    # The key is passed to the Red Hat Enterprise Linux CoreOS (RHCOS) nodes through 
    # their Ignition config files and is used to authenticate SSH access to the nodes. 
    # The key is added to the ~/.ssh/authorized_keys list for the core user on each node, 
    # which enables password-less authentication.
    - name: Check the ssh key pairs
      ansible.builtin.stat:
        path: ~/.ssh/id_rsa
      register: key_stdout
      ignore_errors: true

    # haproxy is the node which can redirect the traffic to master and worker nodes
    - name: Generate ssh key pair in haproxy
      ansible.builtin.shell: |
        ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa <<< y
      when: not key_stdout.stat.exists

    - name: Get the content of public key
      ansible.builtin.shell: |
        cat ~/.ssh/id_rsa.pub
      register: data

    - name: Get the public key
      ansible.builtin.set_fact:
        ssh_pub_key: "{{ data.stdout }}"

    - name: Install haproxy
      ansible.builtin.include_tasks:
        file: install-haproxy.yml

    - name: Generate OCP config
      ansible.builtin.include_tasks:
        file: generate-ocp-config.yml

    - name: Print the url for node installation
      ansible.builtin.debug:
        msg: "coreos-installer install /dev/sda --insecure-ignition \
          --ignition-url=http://{{ haproxy_ip }}:8080/ocp/bootstrap.ign \
          --copy-network"

    - name: Check all fqdn for OCP
      ansible.builtin.include_tasks:
        file: check_fqdn.yml
      loop: "{{ apis }}"

    - name: Check ip address of nodes
      ansible.builtin.include_tasks:
        file: check_node_ip.yml
      loop:
        - "{{ masters | dict2items }}"
        - "{{ workers | dict2items }}"
        - "{{ bootstrap | dict2items }}"
