---
  - name: Generate own CA certificate
    shell: |
      cd /etc/ssl
      openssl req -x509 -sha256 -days {{ cert_valid_years }} -newkey rsa:2048 -keyout rootCA.key \ 
      -out rootCA-{{ fqdn }}.crt -nodes -subj \
       "/C=US/ST=New Work/L=New Work/O=My own CA Inc/OU=Own CA/CN=ca.example.com/emailAddress=dev@ca.example.com"

  - name: Generate FQDN key and csr
    shell: |
      cd /etc/ssl
      openssl req -newkey rsa:2048 -keyout domain.key -out domain.csr -nodes \
      -subj "/C=US/ST=New Work/L=New Work/O=Self Signed Inc/OU=Self Signed/CN={{ fqdn }}/emailAddress=dev@{{ fqdn }}"

  - name: Copy template to /etc/ssl
    template:
      src: server/domain.ext.j2
      dest: /etc/ssl/domain.ext

  - name: Sign the cert with own CA
    shell: |
      cd /etc/ssl
      openssl x509 -req -CA rootCA-{{ fqdn }}.crt -CAkey rootCA.key -in domain.csr -out domain.crt \
      -days {{ cert_valid_years }} -CAcreateserial -extfile domain.ext

  - name: Download the root CA file
    ansible.builtin.fetch:
      src: /etc/ssl/rootCA-{{ fqdn }}.crt
      dest: rootCA-{{ fqdn }}.crt
      flat: yes
  
  