---
- hosts: bind
  tasks:

    - name: Add zone
      lineinfile:
        path: /etc/named/db.{{ domain }}
        line: "{{ alias }}\t\tIN\t\tA\t\t{{ ip }}"

    - name: Reload named
      service:
        name: named
        state: reloaded
