---
- hosts: all
  ignore_errors: true
  tasks:
    - name: service stop
      service:
        name: kubelet
        state: stopped

    - name: uninstall k8s packages
      yum:
        name: "{{ item }}"
        state: absent
      loop:
        - kubectl
        - kubeadm
        - kubelet

    - reboot:

    - name: remove files
      command: "rm -rf  /var/lib/etcd /var/lib/kubelet /etc/kubernetes /etc/yum.repos.d/k8s.repo"