---

- include_tasks: powerstate.yml
  vars:
    state: "shutdown"
  when: action == "shutdown"

- block:
    - include_tasks: gather-vm-info.yml
    - include_tasks: unregister.yml
  when: action == "unregister"

- include_tasks: register.yml
  when: action == "register"

- include_tasks: powerstate.yml
  vars:
    state: "poweron"
  when: action == "poweron"

- include_tasks: gather-vm-info.yml

# - name: Gather vmware host facts from vCenter
#   community.vmware.vmware_host_facts:
#     hostname: "{{ vcenter_hostname }}"
#     username: "{{ vcenter_username }}"
#     password: "{{ vcenter_password }}"
#     validate_certs: False
#     esxi_hostname: "10.1.23.102"
#   register: host_facts
#   delegate_to: localhost

# - debug:
#     msg: "{{ host_facts }}"

# - name: Gather info from datacenter about specific datastore
#   community.vmware.vmware_datastore_info:
#     hostname: '{{ vcenter_hostname }}'
#     username: '{{ vcenter_username }}'
#     password: '{{ vcenter_password }}'
#     validate_certs: False
#     datacenter_name: '{{ vcenter_datacenter }}'
#     name: "datastore1 (1)"
#   delegate_to: localhost
#   register: info

# - debug:
#     msg: "{{ info }}"