---
- name: create k8s yum repo
  template:
    src: templates/k8s.repo.new
    dest: "/etc/yum.repos.d/k8s.repo"

- name: yum install kubelet kubeadm kubectl
  yum:
    name: "{{ item }}"
    state: present
  loop: [ "kubelet", "kubeadm", "kubectl" ]

- name: yum install net-tools
  yum:
    name: "net-tools"
    state: latest

- name: Update /etc/hosts
  lineinfile:
    path: "/etc/hosts"
    line: "{{  hostvars[item]['inventory_hostname'] }} {{  hostvars[item]['ansible_nodename'] }}"
    state: present
    backup: yes
  loop: "{{ groups['nodes'] }}"

- name: start kubelet service
  service:
    name: kubelet
    state: started
    enabled: true

- name: add env variable for kubectl
  blockinfile:
    path: "/etc/profile"
    block: |
        alias k=kubectl
    state: present
    backup: yes
