---
- name: Open firewall ports
  command: "firewall-cmd --add-port={{ item }}/tcp --permanent"
  loop: ["6443", "2379-2380", "10250", "10259", "10257"]
  when: inventory_hostname in groups['masters']

- name: Open firewall ports
  command: "firewall-cmd --add-port={{ item }}/tcp --permanent"
  loop: ["10250", "30000-65535"]
  when: inventory_hostname in groups['workers']

- command: "firewall-cmd --reload"

- name: reboot vm
  reboot:
    reboot_timeout: 600
