---
- hosts: all
  vars_files:
    - vars.yaml
  gather_facts: false
  any_errors_fatal: true
  become: true
  tasks:
    - name: Check the previous commit file
      ansible.builtin.shell: |
        test -f "{{ root_path }}/{{ item }}/last-main-commit"
      loop: "{{ projects }}"

    - name: Clone the main branches
      ansible.builtin.git:
        repo: "git@github.com:sg-wireless/{{ item }}.git"
        dest: "{{ root_path }}/{{ item }}/main"
        single_branch: yes
        version: main
        key_file: "/home/sguser/.ssh/id_rsa_github"
        accept_newhostkey: true
      loop: "{{ projects }}"

    - name: Get git log commit
      ansible.builtin.shell: |
        cd "{{ root_path }}/{{ item }}/main"
        git log | head -1 | awk '{print $2}'
      register: main_commit
      loop: "{{ projects }}"

    - name: Print main commit
      ansible.builtin.set_stats:
        data:
          "gateway": "{{ item.stdout }}"
        per_host: no
      loop: "{{ main_commit['results'] }}"

    - name: Compare current commit with last-main-commit
      ansible.builtin.shell: |
        last_commit=$(cat {{ root_path }}/{{ item.item }}/last-main-commit)
        if [ "$last_commit" == "{{ item.stdout }}" ]
        then
          exit 1  # main commit no diff so stop build and deploy.
        else
          exit 0
        fi
      args:
        executable: /usr/bin/bash
      loop: "{{ main_commit['results'] }}"
      loop_control:
        label: "rc"
