---
- hosts: all
  vars_files:
    - vars.yaml
  gather_facts: false
  become: true
  tasks:
    - name: Remove the clone repo
      ansible.builtin.shell: |
        rm -rf "{{ root_path }}/{{ item }}/main"
      loop: "{{ projects }}"

    - name: update the json file for next comparion
      ansible.builtin.lineinfile:
        path: "{{ root_path }}/last-main-commits.json"
        regexp: '^(\s+"{{ item }}":\s)(.*)'
        line: '\1"{{ gateway }}"'
        backrefs: yes
      loop: "{{ projects }}"

    - name: Check file format
      command: jq . "{{ root_path }}/last-main-commits.json"