---
# Run the tasks in control node
- hosts: all
  vars_files:
    - vars.yml
  gather_facts: True

  tasks:
    - block:
      - name: Stop all mysqld
        service:
          name: mysqld
          state: stopped

      - name: Remove yum packages
        yum:
          name: mysql-server
          state: absent
      rescue:
        - debug:
            msg: "This always executes."

    - name: Remove db files
      file:
        path: /var/lib/mysql
        state: absent

    - name: Install mysql db
      yum:
        name: mysql-server
        state: present

    - name: Start all mysqld
      service:
        name: mysqld
        state: started
        enabled: True
